**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

In [4]:
import numpy as np

In [22]:
a = np.array(
    [11.7, 20, 325, 10.2, 11.7, 20]
)  # - créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]

a[0] = 5  # remplacez la première occurence de la valeur 11.7 par 5
a = np.where(a == 20, 0, a)  # - remplacez toutes les occurences des valeurs 20 par 0
print(a.nbytes)
a = a.astype(np.uint8)  #
print(a.size)
print(a)


48
6
[ 5  0 69 10 11  0]


# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

In [37]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, np.nan]])
print(b.dtype)
print("-" * 50)
print(b.shape)
print("-" * 50)
print(b.ndim)
print("-" * 50)
print(b.size)
print("-" * 50)
print("oui")
print("-" * 50)
print(b * np.array([[1, 1, 1], [1, 1, 1], [5, 5, 5]]))
print("-" * 50)
try:
    b / np.array([[1, 1, 1], [1, 1, 1], [0, 0, 0]])
except Exception as e:
    print(e)

b.astype(np.int32)


float64
--------------------------------------------------
(3, 3)
--------------------------------------------------
2
--------------------------------------------------
9
--------------------------------------------------
oui
--------------------------------------------------
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [35. 40. nan]]
--------------------------------------------------


C:\Users\thoma\AppData\Local\Temp\ipykernel_25628\2945736864.py:15: RuntimeWarning: divide by zero encountered in divide
  b / np.array([[1, 1, 1], [1, 1, 1], [0, 0, 0]])
C:\Users\thoma\AppData\Local\Temp\ipykernel_25628\2945736864.py:19: RuntimeWarning: invalid value encountered in cast
  b.astype(np.int32)


array([[          1,           2,           3],
       [          4,           5,           6],
       [          7,           8, -2147483648]])

# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [70]:
c = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
d = c[1:, 1:]
d[0, 0] = 0
print(d)
print("-" * 50)
print(c)


[[ 0 60]
 [80 90]]
--------------------------------------------------
[[10 20 30]
 [40  0 60]
 [70 80 90]]


# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x4 par 99
4. Réafficher x3

In [68]:
e = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
f = e[1:, 1:]
f = np.where(f == 50, 99, f)
print(f)
print("-" * 50)
print(e)


[[99 60]
 [80 90]]
--------------------------------------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]


# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

In [71]:
g = np.random.randint(2, 8, (4, 4))
print(g)


[[5 4 3 7]
 [2 2 3 3]
 [2 6 2 5]
 [6 6 6 5]]


# Exercice 6

- reproduire la matrice suivante (sans les noms de lignes ou colonnes)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>